<?php

/**
 * @file
 * Hooks for node_layout module.
 */

/**
 * Implements hook_entity_info().
 */
function node_layout_entity_info() {
  $info['node_layout'] = array(
    'label' => t('Node Layout'),
    'base table' => 'node_layout',
    'entity class' => 'NodeLayoutEntity',
    'controller class' => 'NodeLayoutEntityController',
    'entity keys' => array(
      'id' => 'id',
    ),
    'fieldable' => FALSE,
    'uuid' => FALSE,
  );

  return $info;
}

/**
 * Implements hook_autoload_info().
 */
function node_layout_autoload_info() {
  return array(
    'NodeLayoutEntity' => 'src/entity/node_layout.entity.inc',
    'NodeLayoutEntityController' => 'src/entity/node_layout.entity.inc',
    'NodeLayoutEntityControllerInterface' => 'src/entity/node_layout.entity.inc',
  );
}

/**
 * Implements hook_menu().
 */
function node_layout_menu() {
  $items = array();

  $items['node/%/layout'] = array(
    'title' => 'Layout',
    'description' => 'Edit Node Layout',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('node_layout_edit_form'),
    //    'access arguments' => array('edit node layouts'),
    'access callback' => 'node_layout_edit_access_callback',
    'file' => 'node_layout.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['node_layout_titles/autocomplete'] = array(
    'page callback' => '_node_layout_title_autocomplete',
    'access arguments' => 'access content',
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/content/node-layout'] = array(
    'title' => 'Node Layout Settings',
    'description' => 'Configuration options for the Node Layout module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('node_layout_settings_form'),
    'access arguments' => array('administer node layout'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 0,
    'file' => 'node_layout.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function node_layout_theme($existing, $type, $theme, $path) {
    return array(
      'node_layout_edit_layout' => array(
        'variables' => array('data' => NULL),
        'template' => 'templates/edit_layout'
      ),
    );
}

/**
 * Implements hook_block_info().
 */
function node_layout_block_info() {
  $blocks = array();
  $regions = node_layout_get_active_regions();

  foreach ($regions as $region) {
    $blocks["node_layout_$region"] = array(
      'info' => "Node Layout Block: $region",
      'description' => t('The hierarchical list...'),
//      'cache' => BACKDROP_NO_CACHE,
    );
  }

  return $blocks;
}

/**
 * Implements hook_preprocess_page().
 */
//function node_layout_preprocess_page(&$variables) {
//  // Add the JS and CSS assets if the page is supposed to have code syntax highlighting.
//  $nid = explode('/', current_path())[1];
//  $node = node_load($nid);
//  if ($node && node_layout_is_type_available($node->type)) {
//    backdrop_add_css(backdrop_get_path('module', 'highlightjs_wysiwyg')
//      . '/libraries/highlightjs/styles/' . config_get('highlightjs_wysiwyg.settings','csh_theme') . '.css');
//    backdrop_add_css(backdrop_get_path('module', 'highlightjs_wysiwyg')
//      . '/css/csh.css');
//
//    backdrop_add_js(backdrop_get_path('module', 'highlightjs_wysiwyg')
//      . '/libraries/highlightjs/highlight.pack.js');
//    backdrop_add_js('jQuery(document).ready(function () { hljs.initHighlightingOnLoad(); });', array(
//      'type' => 'inline',
//      'scope' => 'footer',
//    ));
//  }
//}

/**
 * Implements hook_block_view().
 */
function node_layout_block_view($delta = '', $settings = array()) {

  $item = menu_get_item();
  if (strpos($delta, 'node_layout') !== -1 && $item['path'] === 'node/%') {
    $node = menu_get_object('node');
    $layout = node_layout_get_layout($node->id);

    if ($layout->regions) {
      switch ($delta) {
        case 'node_layout_header':
          $nid = explode('/', $layout->regions['header']['reference'])[1];
          if ($nid) {
            $block['content'] = node_view(node_load($nid));
            $block['subject'] = 'header block';
            return $block;
          }

          break;
        case 'node_layout_sidebar':
          $nid = explode('/', $layout->regions['sidebar']['reference'])[1];
          if ($nid) {
            $block['content'] = node_view(node_load($nid));
            $block['subject'] = 'sidebar block';
            return $block;
          }

          break;
        case 'node_layout_bottom':
          $nid = explode('/', $layout->regions['bottom']['reference'])[1];
          if ($nid) {
            $block['content'] = node_view(node_load($nid));
            $block['subject'] = 'bottom block';
            return $block;
          }

          break;
      }
    }
  }
}

/**
 * Gets the layout for the node in question.
 *
 * @return array|bool|mixed|null
 */
function node_layout_get_layout($nid) {
  $layout = &backdrop_static(__FUNCTION__);

  if ($layout === NULL) {
    $layout = db_query('SELECT * FROM {node_layout} WHERE nid = :nid', array(':nid' => $nid))->fetch();
    $layout->regions = unserialize($layout->data);
  }

  return $layout;
}

/**
 * Gets active regions the layout tool can use.
 *
 * @return array
 */
function node_layout_get_active_regions(string $node_type) {
  // Get the node layout.
  $node_layout = layout_load('default');

  $config = config_get('node_layout.settings');
  $region = $node_type . '_regions';
  if (!isset($config[$region])) {
    return [];
  }

  return array_filter($config[$region], function ($region) {
    return $region !== 0;
  });
}

function node_layout_is_type_available($type = '') {
  if ($type === '') {
    return NULL;
  }

  $config = config_get('node_layout.settings');
  return in_array($type, array_values($config['available_node_types']), TRUE);
}

function node_layout_get_available_node_types() {
  $config = config_get('node_layout.settings');
  return $config['available_node_types'];
}

function node_layout_get_template() {

}

/**
 * Return suggestions for path autocomplete.
 *
 * @param string $search
 *   The search result.
 */
function _node_layout_title_autocomplete($search) {
  $matches = array();

  // Query node table based on titles.
  $query = db_select('node', 'n');

  $results = $query->fields('n')
    ->fields('n', array('title'))
    ->condition('n.title', '%' . db_like($search) . '%', 'LIKE')
    ->range(0, 10)
    ->execute();

  // Add results to JSON output. "Node path" => "node type: node title (node ID)".
  foreach ($results as $result) {
    $matches['node/' . $result->nid] = check_plain($result->type . ': ' . $result->title . ' (' . $result->nid . ')');
  }

  backdrop_json_output($matches);
}
